stages:
  data_ingestion:
    cmd: python3 src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python3 src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python3 src/feature_engineering.py
    deps:
    - data/processed
    - src/feature_engineering.py
    outs:
    - data/features
  model_building:
    cmd: python3 src/model_building.py
    deps:
    - data/features/
    - src/model_building.py
    outs:
    - model.pkl
  model_evaluation:
    cmd: python3 src/model_evaluation.py
    deps:
    - model.pkl
    - src/model_evaluation.py
    metrics:
    - metrics.json
