stages:
  data_ingestion:
    cmd: python3 src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python3 src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed
